group:
  # All repositories
  - files:
      - source: .github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitignore
        dest: .gitignore
      - source: .vscode/json.code-snippets
        dest: .vscode/json.code-snippets
      - source: .vscode/settings.json
        dest: .vscode/settings.json
      - source: .vscode/extensions.json
        dest: .vscode/extensions.json
      - source: .github/pull_request_template.md
        dest: .github/pull_request_template.md
      - source: .github/workflows/auto-author-assign.yml
        dest: .github/workflows/auto-author-assign.yml
    repos: |
      seedcase-project/seedcase-sprout
      seedcase-project/seedcase-website
      seedcase-project/seedcase-theme
      seedcase-project/community
      seedcase-project/design
      seedcase-project/team
      seedcase-project/data
      seedcase-project/decisions

  # Python Django project repositories
  - files:
      # Actions
      - source: common/actions/dependabot.yml
        dest: .github/dependabot.yml
      - source: common/actions/deploy-pr-preview.yml
        dest: .github/workflows/deploy-pr-preview.yml
      - source: common/actions/deploy-demo.yml
        dest: .github/workflows/deploy-demo.yml
      - source: common/actions/deploy-docs.yml
        dest: .github/workflows/deploy-docs.yml
      
      # VSCode Settings
      - source: .vscode/google-notypes.mustache
        dest: .vscode/google-notypes.mustache
      - source: .vscode/python.code-snippets
        dest: .vscode/python.code-snippets
      - source: .vscode/launch.json
        dest: .vscode/launch.json
      
      # Misc
      - source: common/justfile/django
        dest: justfile
      - source: common/ruff.toml
        dest: ruff.toml
      - source: common/LICENSE.md
        dest: LICENSE.md
    repos: |
      seedcase-project/seedcase-sprout

  # Website repositories
  - files:
      - source: common/justfile/web
        dest: justfile
      - source: common/devcontainers/web.json
        dest: .devcontainer/devcontainer.json
      - source: .github/workflows/deploy-website.yml
        dest: .github/workflows/deploy-website.yml
    repos: |
      seedcase-project/seedcase-website
      seedcase-project/design
      seedcase-project/community
      seedcase-project/team
      seedcase-project/decisions
