group:
  # All repositories
  - files:
      - source: .github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitignore
        dest: .gitignore
      - source: .vscode/json.code-snippets
        dest: .vscode/json.code-snippets
      - source: .vscode/settings.json
        dest: .vscode/settings.json
      - source: .vscode/extensions.json
        dest: .vscode/extensions.json
      - source: .github/workflows/add-to-project.yml
        dest: .github/workflows/add-to-project.yml
    repos: |
      seedcase-project/seedcase-website
      seedcase-project/seedcase-theme
      seedcase-project/community
      seedcase-project/design
      seedcase-project/team
      seedcase-project/data
      seedcase-project/decisions

  # Website repositories
  - files:
      - source: .github/pull_request_template.md
        dest: .github/pull_request_template.md
      - source: common/justfile/web
        dest: justfile
      - source: common/devcontainers/web.json
        dest: .devcontainer/devcontainer.json
      - source: common/actions/deploy-website.yml
        dest: .github/workflows/deploy-website.yml
    repos: |
      seedcase-project/seedcase-website
      seedcase-project/design
      seedcase-project/community
      seedcase-project/team
      seedcase-project/decisions
