group:
  # All repositories
  - files:
      - source: .github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitignore
        dest: .gitignore
      - source: .vscode/json.code-snippets
        dest: .vscode/json.code-snippets
      - source: .vscode/settings.json
        dest: .vscode/settings.json
      - source: .vscode/extensions.json
        dest: .vscode/extensions.json
      - source: .github/workflows/auto-author-assign.yml
        dest: .github/workflows/auto-author-assign.yml
    repos: |
      seedcase-project/seedcase-sprout
      seedcase-project/seedcase-project
      seedcase-project/seedcase-theme
      seedcase-project/community
      seedcase-project/design
      seedcase-project/team
      seedcase-project/data
      seedcase-project/decisions

  # Python Django project repositories
  - files:
      - source: common/python-style.yml
        dest: .github/workflows/python-style.yml
      - source: .vscode/python.code-snippets
        dest: .vscode/python.code-snippets
      - source: common/justfile/django
        dest: justfile
      - source: common/ruff.toml
        dest: ruff.toml
    repos: |
      seedcase-project/seedcase-sprout

  # Website repositories
  - files:
      - source: common/justfile/web
        dest: justfile
      - source: common/devcontainers/web.json
        dest: .devcontainer/devcontainer.json
    repos: |
      seedcase-project/seedcase-project
      seedcase-project/design
      seedcase-project/community
      seedcase-project/team
      seedcase-project/decisions
