name: Add to project board

on:
  issues:
    types:
      - opened
  pull_request: 
    types:
      - opened

jobs:
  add-to-project:
    uses: seedcase-project/.github/.github/workflows/add-to-project-action.yml@main
    secrets: 
      gh-token: ${{ secrets.GITHUB_TOKEN }}
