name: Deploy documentation as website

on:
  issues:
    types:
      - opened
  pull_request: 
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BOARD: "Team project planning"
    steps:
      - name: Add issue to project board
        if: ${{ github.event_name == 'issue' }}
        runs: gh issue edit $ISSUE --add-project $BOARD
        env:
          ISSUE: ${{ github.event.issue.html_url }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          PR: ${{ github.event.pull_request.html_url }}

      # add software dependencies here

      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.netlify-token }}
