name: Deploy documentation as website

on:
  workflow_call:
    secrets:
      netlify-token:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # add other software dependencies here

      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.netlify-token }}
