name: Check, test, and build Python package

on:
  workflow_call:

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          # uv recommends to set the version for best practice.
          version: "0.6.13"
          # To have a faster CI time, enable cache between runs.
          enable-cache: true
          # Reset the cache if the lock file changes.
          cache-dependency-glob: "uv.lock"

      - name: Install justfile
        run: sudo apt-get install -y just

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project and it's dependencies
        run: just install-deps

      - name: Check Python style
        run: just check-python

      - name: Run tests and coverage
        run: just test-python

      - name: Prepare repo for coverage report
        run: |
            # So that folder can be committed
            rm htmlcov/.gitignore

      - name: Push coverage report and badge to branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: coverage
          folder: htmlcov
          # Keep a simple Git history
          single-commit: true

      - name: Run security checks
        run: just check-security

      - name: Run spell checker
        run: just check-spelling

      - name: Run unused code checker
        run: just check-unused


