name: Check and build package

on:
  workflow_call:

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3

      - name: Install justfile
        run: sudo apt-get install -y just

      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project and it's dependencies
        run: just install-deps

      - name: Check Python style
        run: just check-python

      - name: Run tests and coverage
        run: just test-python

      - name: Prepare repo for coverage report
        run: |
            # So that folder can be committed
            rm htmlcov/.gitignore

      - name: Push coverage report and badge to branch
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: coverage
          folder: htmlcov
          # Keep a simple Git history
          single-commit: true

      - name: Run security checks
        run: just check-security

      - name: Run spell checker
        run: just check-spelling

      - name: Run unused code checker
        run: just check-unused
