name: Run Python tests

on:
  workflow_call:

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python (with cache for Poetry)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies with Poetry
        run: poetry install --no-interaction

      - name: Run unit tests
        run: poetry run pytest
