name: Build website

on:
  workflow_call:
    inputs:
      hosting-provider:
        description: "Hosting provider to use for publishing the website: netlify or gh-pages. If 'gh-pages', also need to set permissions."
        required: false
        type: string
        default: 'netlify'
    secrets:
      netlify-token:
        required: false
      github-token:
        # Needs permissions: contents: write, pages: write
        required: false

jobs:
  build-website:
    runs-on: ubuntu-latest
    concurrency:
      group: build-website-python-group
      cancel-in-progress: true
    env:
        QUARTO_PYTHON: ".venv/bin/python3"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          # Install a specific version of uv.
          # uv recommends to set the version for best practice.
          version: "0.6.13"
          # To have a faster CI time, enable cache between runs.
          enable-cache: true
          # Reset the cache if the lock file changes.
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project and it's dependencies
        run: |
            uv sync --all-extras --dev
            echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0

      - name: Spell check repo
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0

      - name: Build function reference docs
        run: uv run quartodoc build

      - name: Publish to Netlify (and render)
        if: ${{ inputs.hosting-provider == 'netlify' }}
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.netlify-token }}

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see above).
      - name: Publish to GitHub Pages (and render)
        if: ${{ inputs.hosting-provider == 'gh-pages' }}
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
