name: Test template
on:
  workflow_call:
    inputs:
      # The justfile recipe that will run the template tests.
      test-recipe:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          enable-cache: true

      - name: Install justfile
        run: sudo apt install -y just

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "fake@example.com"

      - name: Test and check template creation
        run: just ${TEST_RECIPE}
        env:
          TEST_RECIPE: ${{ inputs.test-recipe }}
