name: Add to project board and add assignee

on:
  workflow_call:
    inputs:
      board-number:
        required: true
        type: number
      app-id:
        type: "string"
        required: true
    secrets:
      add-to-board-token:
        required: true
      gh-token:
        required: true

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.add-to-board-token }}

      - name: Add issue or PR to project board
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/${{ inputs.board-number }}
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Assign PR to creator
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          gh pr edit $PR --add-assignee $AUTHOR --repo $REPO
        env:
          REPO: ${{ github.repository }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          PR: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.gh-token }}
