name: Test template
on:
  workflow_call:
    inputs:
      # The justfile recipe that will run the template tests.
      test-recipe:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          enable-cache: true

      - name: Install justfile
        run: sudo apt install -y just

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "fake@example.com"

      - name: Test and check template creation
        run: just ${TEST_RECIPE}
        env:
          TEST_RECIPE: ${{ inputs.test-recipe }}
